name: Demo Python with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    container:
      image: python:3.11-slim
      options: --user root

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        apt-get update
        # Ensure curl is installed along with other dependencies
        apt-get install -y --no-install-recommends docker.io curl wget software-properties-common
        # Install dependencies required by Playwright
        apt-get install -y wget software-properties-common
        # Add Node.js to apt sources
        curl -sL https://deb.nodesource.com/setup_14.x | bash -
        # Install Node.js and npm
        apt-get install -y nodejs
        # Install system dependencies required by Playwright browsers
        apt-get install -y libgtk-3-0 libgbm-dev libnss3 libasound2
      shell: bash
    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry lock --no-update
        poetry install --no-ansi --no-root
    
    - name: Install Playwright and browsers
      run: |
        # Install Playwright Python package
        pip install playwright
        # Install Playwright browsers
        python -m playwright install

    - name: Run tests
      run: |
        . .venv/bin/activate
        .venv/bin/python -m pytest